# Generated by Django 5.2.8 on 2025-11-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendices',
            name='cedula',
            field=models.CharField(default='*********', max_length=15),
        ),
    ]
