# Generated by Django 4.2.26 on 2025-12-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_aprendices_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendices',
            name='programa',
            field=models.CharField(max_length=255),
        ),
    ]
