# Generated by Django 4.2.26 on 2025-12-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('T.I', 'Tarjeta de Identidad'), ('C.E', 'Cédula de Extranjería'), ('P.A', 'Pasaporte')], default='C.C', max_length=3, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad o Área')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad de Residencia')),
                ('nivel_formacion', models.CharField(choices=[('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado'), ('N.A', 'No Aplica')], default='N.A', max_length=3, verbose_name='Nivel de Formación')),
                ('experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Instructor Activo')),
                ('fecha_vinculacion', models.DateField(verbose_name='Fecha de Vinculación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructores.programa', verbose_name='Programa Asignado')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
    ]
