# Generated by Django 4.2.26 on 2025-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='tipo_doc',
            field=models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('P.A', 'Pasaporte')], default='C.C', max_length=3, verbose_name='Tipo de Documento'),
        ),
    ]
